---
http_interactions:
- request:
    method: get
    uri: https://api.yotpo.com/apps/3ovRYNIb6OIAI0ddS7EfpYkHpi0oTKl6bj82Vjiy/features/11/feature_settings?utoken=Ufo5XkKXNsuh0k9ZMPndRv4DlV9324ptg730KKqC
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Yotpo-Api-Connector:
      - Ruby0.1.0
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      Server:
      - nginx/1.8.1
      Date:
      - Tue, 24 May 2016 07:25:15 GMT
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '549'
      Connection:
      - keep-alive
      Yotpo-Parsed-Request:
      - '{"action":"index","controller":"owners_features_settings","app_id":"3ovRYNIb6OIAI0ddS7EfpYkHpi0oTKl6bj82Vjiy","feature_id":"11"}'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Etag:
      - '"8280394d71b18294de0e74800bef5244"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 2a39dbb82025bba6d9ba6ec3e4662bec
      X-Runtime:
      - '7.943306'
      Access-Control-Allow-Credentials:
      - 'true'
    body:
      encoding: UTF-8
      string: '{"status":{"code":200,"message":"OK"},"response":{"widget_size":{"unit":"percentage","value":100},"font_size":"14","font_type":"Open
        Sans","background_color":{"transparent":true,"color":"#ffffff"},"color_primary":"#3085c7","color_d1":"#26649f","color_d2":"#1d5077","color_l1":"#599dd2","color_l2":"#83b6dd","color_l3":"#accee9","color_l4":"#d6e7f4","color_stars":"#ffd200","color_text_white":"#ffffff","theme":"light","color_text_gray_light":"#e3e3e3","color_text_gray":"#a2a2a2","color_text_gray_dark":"#737373","color_text_gray_darker":"#4f4f4f"}}'
    http_version: 
  recorded_at: Tue, 24 May 2016 07:25:15 GMT
recorded_with: VCR 2.9.3
